### ISSUE TITLE
Add a Reloader for faster updates of rendered pages

### ISSUE THREAD

**Issue by andrewindechemain** [DemocracyLab/CivicTechExchange#927] opened 2022-11-17 20:13 UTC
Currently, when making changes to the codebase locally a user may need to rebuild the docker container so that the changes take place. We need to install a reloader dependency that instantly makes changes to rendered pages whenever edits are made to the code. Currently, React has adopted react-refresh which works out of the box once installed.

**Comment by AdrielMaximus** [comment] 2023-04-01 19:44
i tried my best

const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin');
module.exports = {
  plugins: [
    new ReactRefreshWebpackPlugin()
  ],
  devServer: {
    hot: true,
  },
};

**Comment by PeterBreen** [comment] 2023-08-17 16:52
this looks like the same issue as described in #477

**Comment by marlonkeating** [comment] 2023-08-17 17:06
Closing as duplicate of https://github.com/DemocracyLab/CivicTechExchange/issues/477

**Closed by marlonkeating** 2023-08-17 17:06 UTC
Labels: Front End
